#!/bin/bash

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INSTALL_PATH="$SCRIPT_PATH/root"

export PATH="$INSTALL_PATH/bin:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/armv7a-hardfloat-linux-uclibceabi/binutils-bin/2.25.1:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/armv7a-hardfloat-linux-uclibceabi/gcc-bin/4.9.3:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/mips-unknown-linux-musl/binutils-bin/2.25.1:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/mips-unknown-linux-musl/gcc-bin/5.3.0:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/x86_64-gentoo-linux-musl/binutils-bin/2.25:$INSTALL_PATH/usr/x86_64-pc-linux-gnu/x86_64-gentoo-linux-musl/gcc-bin/4.9.3:$PATH"
export LD_LIBRARY_PATH="$INSTALL_PATH/lib:$LD_LIBRARY_PATH"

unset INSTALL_PATH
unset SCRIPT_PATH
